-- Database

CREATE DATABASE IF NOT EXISTS Agenda;
USE Agenda;

CREATE USER IF NOT EXISTS 'PHPeSQL'@'localhost' IDENTIFIED BY "123321";
GRANT ALL PRIVILEGES ON Agenda.* TO 'PHPeSQL'@'localhost';

FLUSH PRIVILEGES;

-- Tables

CREATE TABLE IF NOT EXISTS Contacts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    phone VARCHAR(20)
);